<?php echo $this->doctype(); ?>
<!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="es"> <![endif]-->
<!--[if IE 7]>    <html class="lt-ie9 lt-ie8" lang="es"> <![endif]-->
<!--[if IE 8]>    <html class="lt-ie9" lang="es"> <![endif]-->
<!--[if gt IE 8]> <html lang="es"> <![endif]-->
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <title>Municipalidad La Molina</title>
  <meta name="title" content="Municipalidad La Molina"/>
  <meta name="description" content="Municipalidad La Molina"/>
  <meta name="keywords" content="municipalidad, la molina"/>
  <meta name="author" content="onlinestudioproductions.com"/>
  <meta name="viewport" content="width=device-width"/>
  <meta name="language" content="es"/>
  <meta name="robots" content="noindex"/>
  <link type="text/css" rel="stylesheet" href="<?php echo $this->basePath("css/admin.css")?>"/>
  <link href='http://fonts.googleapis.com/css?family=Cuprum' rel='stylesheet' type='text/css' />
  <!--[if lt IE 9]><script src="<?php echo $this->basePath("js/libs/html5shiv.js")?>"></script><![endif]-->
</head>
<body>
	<header>
            <div class="fix">
              <div class="box-center">
                <div class="head-user">
                  <span></span>Hola, <?php echo $this->session->name ?>
                </div>
                <ul class="head-options">
                  <li>
                      <a title="Cambiar Password" href="/password"><span ></span>Password</a>
                  </li>
                  <li>
                      <a title="Perfil" href="/micuenta"><span class="ichd-perfil"></span>Perfil</a>
                  </li>
                  <li>
                    <a title="Logout" href="/logout"><span class="ichd-logout"></span>Logout</a>
                  </li>
                </ul>
              </div>
            </div>
          </header>
	<div id="wrapper">
		<aside class="sidebar">
			<img class="side-logo" src="<?php echo $this->basePath("img/logo.png"); ?>" width="212" height="60" />
			<ul class="admin-menu">
                            <li>
                                <a title="Dashboard" href="/" class="active"><span class="icad-dashb"></span>Dashboard</a>
                            </li>
                            <li>
                                <a title="Eventos" href="/" ><span class="icad-prom"></span>Eventos</a>
                            </li>
                             <li>
                                <a title="Denuncias" href="/complaint" ><span class="icad-prom"></span>Denuncias</a>
                            </li>
                    </ul>
		</aside>
		<div class="container">
			<?php echo $this->content; ?>
		</div>
	</div>
	<footer>
            <div class="box-center">
                    <p>©Copyright 2013. Todos los derechos reservados. Este admin fué desarrollado por <a target="_blank" href="http://www.onlinestudioproductions.com/">OnlineStudioProductions</a></p>
            </div>
        </footer>
        <script type="text/javascript">
            var yOSON ={
                "modulo":"<?php echo $this->module?>",
                "controller":"<?php echo $this->controller?>",
                "action":"<?php echo $this->action?>",
                "baseHost":"",
                "statHost":"",
                "statVers":"?vcx27w",
                "min":"","AppCore":{},"AppSandbox":{},"AppSchema":{"modules":{},"requires":{}}
              };
        </script>
	<script src="<?php echo $this->basePath("js/libs/framework.js");?>"></script>
	<script src="<?php echo $this->basePath("js/application/yoson.js");?>"></script>
	<script src="<?php echo $this->basePath("js/modules/admin.js");?>"></script>
	<script src="<?php echo $this->basePath("js/application/schemas/modules.js");?>"></script>
	<script src="<?php echo $this->basePath("js/application/appLoad.js");?>"></script>
</body>
</html>