<div class="content-login">
        <?php if ($this->messages) { ?>
            <?php foreach ($this->messages as $message) { ?>
                    <div class="alert">
                        <?php echo $message; ?>
                    </div>
            <?php } ?>
        <?php } ?>
    <div class="login-panel frm-panel">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url(
            'login/process',
            array(
                'action'     => 'authenticate',//'login'//
            )
        ));   
        $form->setAttribute('id', 'usarioAut');      
        $form->setAttribute('class','form-horizontal');
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
            <div class="frm-head">
                <h2><span></span>Ingresa a tu Cuenta</h2>
            </div>
            <div class="control-group">
                <label for="userName" class="control-label">Usuario:</label>
                <div class="controls">
                    <?php  echo $this->formRow($form->get('userName'));?>
                </div>
            </div>
            <div class="control-group">
                <label for="password" class="control-label">Contraseña:</label>
                <div class="controls">
                    <?php echo $this->formRow($form->get('password'));?>
                </div>
            </div>
            <div class="control-group last">
                <div class="control">
                    <button class="btn-admin" type="submit">Ingresa</button>
                </div>
            </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>