<div class="frm-panel">

    <form id="frm-article" action="/agregar-picture" 
          method="post" Enctype="multipart/form-data">

       
       
        <div class="control-group">
            <label class="control-label" for="end">imagen:</label>
            <div class="controls">
                 <input type="file" name="imagen">
            </div>
	</div>
	<div class="control-group last">
            <div class="control">
                <button class="btn-admin" type="submit"></button>
            </div>
	</div>
   </form>
</div>